//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOT
    {
        public int NOT_ID { get; set; }
        public Nullable<int> OGRENCI { get; set; }
        public Nullable<int> DERS { get; set; }
        public Nullable<short> SINAV_1 { get; set; }
        public Nullable<short> SINAV_2 { get; set; }
        public Nullable<short> SINAV_3 { get; set; }
        public Nullable<decimal> ORTALAMA { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBL_DERS TBL_DERS { get; set; }
        public virtual TBL_OGRENCI TBL_OGRENCI { get; set; }
    }
}
